/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2016-04-19 21:36:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.arquitecturajava.DataBaseHelper;
import com.arquitecturajava.Libro;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

public final class MostrarLibros_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("\"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Lista de Libros</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<form> \r\n");
      out.write("\t<select name=\"categoria\">\r\n");
      out.write("\t\t<option value=\"seleccionar\">Seleccionar</option>\r\n");
      out.write("\t\t");

			List<String> listaDeCategorias = null;
			listaDeCategorias = Libro.buscarTodasLasCategorias();
			for (String categoria : listaDeCategorias) {
		
      out.write("\r\n");
      out.write("\t\t\t<option value=\"");
      out.print(categoria);
      out.write('"');
      out.write('>');
      out.print(categoria);
      out.write("</option>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t</select>\r\n");
      out.write("\t<input type=\"submit\" value=\"Filtar\">\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t");

		List<Libro> listaDeLibros = null;
		if(request.getParameter("categoria")==null || request.getParameter("categoria").equals("seleccionar")) {
			listaDeLibros = Libro.buscarTodos();
		}else {
		
			listaDeLibros=Libro.buscarPorCategoria(request.getParameter("categoria"));
			}
		
		for (Libro libro : listaDeLibros) {
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.print(libro.getIsbn());
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.print( libro.getTitulo());
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.print( libro.getCategoria());
      out.write("\r\n");
      out.write("\t<a href=\"BorrarLibro.jsp?isbn=");
      out.print(libro.getIsbn());
      out.write("\">Borrar</a>\r\n");
      out.write("\t<a href=\"FormularioEditarLibro.jsp?isbn=");
      out.print(libro.getIsbn());
      out.write("\">Editar</a>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<a href=\"FormularioInsertarLibro.jsp\">Insertar Libro</a>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
